apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: redis-replica
  namespace: k8s-workshop
spec:
  minReplicas: 1
  maxReplicas: 5
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: redis-replica
  targetCPUUtilizationPercentage: 20
